enum UIStrings {
    static let english: [String: String] = [
        "Установка компонентов": "Component setup",
        "Готово": "Done",
        "Проверка компонентов…": "Checking components…",
        "macOS загружает язык. Дождись завершения…": "macOS is downloading the language. Please wait…",
        "Этот язык недоступен для локального распознавания на этом Mac.": "This language is not available for local recognition on this Mac.",
        "Язык установлен. Распознавание работает без интернета.": "Language installed. Recognition works offline.",
        "Язык ещё не установлен. Для однократной загрузки нужен интернет.": "Language not installed yet. An internet connection is needed for the one-time download.",
        "Не удалось подготовить язык: {0}": "Could not prepare the language: {0}",
        "Текстовый фильтр готов к работе: ему нужен только доступ Accessibility. Компоненты ниже нужны для голоса.": "Text filtering only needs Accessibility permission. The components below are for voice protection.",
        "Установи BlackHole 2ch с сайта разработчика и перезагрузи Mac. Если он уже установлен, повторная установка не нужна.": "Install BlackHole 2ch from its developer’s website and restart your Mac. Skip this if it is already installed.",
        "Скачать BlackHole 2ch": "Download BlackHole 2ch",
        "Сайт и условия BlackHole": "BlackHole website and terms",
        "Загрузить язык через macOS": "Download language via macOS",
        "Проверить снова": "Check again",
        "Загрузка получает языковые данные от Apple. Аудио и текст никуда не отправляются. После установки выбери этот же язык на вкладке голоса.": "The download retrieves language assets from Apple. No audio or text is uploaded. After installation, select the same language in the Voice tab.",
        "Dota 2 устанавливается отдельно через Steam. Для игры выбери системный микрофон или BlackHole 2ch, затем включи голосовую защиту.": "Install Dota 2 separately through Steam. In the game, select the system microphone or BlackHole 2ch, then enable voice protection.",

        "Язык интерфейса": "Interface language",
        "Защита": "Protection",
        "Текстовый чат": "Text chat",
        "Голос · MVP": "Voice · MVP",
        "Стоп перед отправкой": "Pause before sending",
        "Пишешь в Dota. Фильтр проверяет Enter.": "Type in Dota. The filter checks when you press Enter.",
        "ЛОКАЛЬНО": "LOCAL",
        "Выключить защиту": "Turn protection off",
        "Включить защиту": "Turn protection on",
        "Открыть Accessibility…": "Open Accessibility…",
        "Доступ macOS подтверждён приложением": "macOS access confirmed by the app",
        "Переключатель в настройках сам по себе не подтверждает доступ новой сборки.": "The settings switch alone does not confirm access for a new build.",
        "Клавиши Dota: {0}": "Dota keys: {0}",
        "Блокировки: {0}": "Blocked: {0}",
        "Включи фильтр и вернись в Dota": "Enable the filter and return to Dota",
        "Нажми Esc, чтобы закрыть чат и начать с пустой строки.": "Press Esc to close chat and start with an empty draft.",
        "Открой чат обычным Enter и напиши": "Press Enter to open chat and type",
        "Первый прототип рассчитан на стандартные клавиши чата.": "This prototype uses the default chat shortcuts.",
        "Нажми Enter для отправки": "Press Enter to send",
        "Найденные ругательства остановят отправку. Исправь их через Backspace или начни заново через Esc.": "Detected abuse blocks sending. Use Backspace to edit, or Esc to start again.",
        "Экспериментальный режим": "Experimental mode",
        "Поддерживаются набор текста, Backspace и выделение всего через ⌘A / Ctrl+A с удалением или заменой. Вставка, частичное выделение, стрелки, щелчок мыши или смена окна требуют Esc и нового ввода.": "Supports typing, Backspace and ⌘A / Ctrl+A to select all, then delete or replace. After pasting, partial selection, arrow keys, mouse clicks or switching windows, press Esc and start again.",
        "Словарь ловит известные выражения, но не все оскорбления. При закрытии приложения защита прекращается.": "The dictionary catches known expressions, but not all abuse. Quitting the app stops protection.",
        "Полностью локально · без нейросети": "Fully local · no AI model for text",
        "Окно: ⌃⌥Пробел. Закрытие окна не выключает защиту.": "Window: ⌃⌥Space. Closing the window keeps protection on.",
        "Окно можно открыть через значок Dota Tilt Guard в строке меню.": "Open the window using the Dota Tilt Guard menu bar icon.",
        "Выключен": "Off",
        "Событий пока нет": "No events yet",
        "macOS отозвала доступ к вводу. Защита не работает.": "macOS revoked input access. Protection is not working.",
        "Нет доступа — защита не работает": "No access — protection unavailable",
        "Защита выключена": "Protection is off",
        "Защита ожидает подключения": "Waiting to connect",
        "Подключено — ждём клавиши Dota": "Connected — waiting for Dota input",
        "Перехват получает клавиши Dota": "Receiving Dota keyboard input",
        "macOS не подтвердила доступ этой сборке. Если переключатель уже включён, удали Dota Tilt Guard из списка Accessibility и добавь заново.": "macOS has not confirmed access for this build. If the switch is already on, remove Dota Tilt Guard from Accessibility and add it again.",
        "Перехват перезапущен. Нажми Esc в Dota.": "Input capture restarted. Press Esc in Dota.",
        "Перехват был прерван. Нажми Esc перед новым сообщением.": "Input capture was interrupted. Press Esc before typing a new message.",
        "Ожидаю запуска Dota 2": "Waiting for Dota 2 to start",
        "macOS не разрешила перехват событий Dota. Защита не работает.": "macOS did not allow Dota input capture. Protection is not working.",
        "В Dota сначала нажми Esc. Счётчик ниже должен расти при наборе.": "Press Esc in Dota first. The counter below should increase as you type.",
        "macOS не включила перехват. Защита не работает.": "macOS did not enable input capture. Protection is not working.",
        "Перехват прерван. Нужна повторная синхронизация через Esc.": "Input capture interrupted. Press Esc to resynchronize.",
        "Получен Enter": "Enter received",
        "Получен Esc — начало нового чата": "Esc received — ready for a new chat",
        "Получена клавиша Dota": "Dota key received",
        "Готов к новому чату · открытие через Enter": "Ready for a new chat · press Enter to open",
        "Dota Tilt Guard · отправка остановлена": "Dota Tilt Guard · message blocked",
        "Не уверен в содержимом чата. Нажми Esc, открой чат заново и набери сообщение.": "The chat contents are uncertain. Press Esc, reopen chat and type your message again.",
        "Сообщение не отправлено: найдено ругательство или оскорбление. Измени текст или нажми Esc.": "Message blocked: profanity or abuse detected. Edit the text or press Esc.",
        "Пауза в голосе": "A pause in voice chat",
        "Ругательство → тишина → возврат через 3 секунды.": "Abuse → silence → voice returns after 3 seconds.",
        "Отменить": "Cancel",
        "Выключить голосовую защиту": "Turn voice protection off",
        "Включить голосовую защиту": "Turn voice protection on",
        "Тишина на 3 секунды": "Mute for 3 seconds",
        "Микрофон": "Microphone",
        "Срабатывания: {0}": "Detections: {0}",
        "Твой микрофон": "Your microphone",
        "Микрофон не найден": "No microphone found",
        "Язык речи": "Speech language",
        "BlackHole 2ch установлен": "BlackHole 2ch is installed",
        "Нужен виртуальный микрофон BlackHole 2ch": "BlackHole 2ch virtual microphone is required",
        "Обновить устройства": "Refresh devices",
        "Сейчас распознано": "Recognized speech",
        "Здесь появится речь с твоего микрофона.": "Speech from your microphone will appear here.",
        "Как работает MVP": "How the MVP works",
        "Речь распознаётся локально на Mac даже во время блокировки. Новое ругательство продлевает паузу ещё на 3 секунды; тишина и речь без новых срабатываний позволяют голосу вернуться.": "Speech recognition runs locally on your Mac, even while muted. New abuse extends the pause by 3 seconds. Silence or speech without new detections lets your voice return.",
        "При включении системным микрофоном становится BlackHole 2ch. Фильтр действует в приложениях, использующих системный вход. Явно выбранный в игре другой микрофон обходит его.": "Enabling protection sets BlackHole 2ch as the system microphone. The filter applies to apps using the system input. A different microphone selected in the game bypasses it.",
        "Первое слово может проскочить до распознавания. При выключении защиты возвращается прежний системный микрофон.": "The first word may get through before recognition. Turning protection off restores the previous system microphone.",
        "Без записи аудио и истории · локальные модели macOS": "No audio recordings or history · local macOS models",
        "Голосовая защита выключена": "Voice protection is off",
        "Голосовая защита выключена.": "Voice protection is off.",
        "Подготовка микрофона…": "Preparing microphone…",
        "Передача отключена · нужна проверка": "Transmission stopped · check required",
        "В игру идёт тишина": "The game receives silence",
        "Голос передаётся": "Voice is being transmitted",
        "Для локального голосового режима нужна macOS 26 или новее.": "Local voice protection requires macOS 26 or later.",
        "Нужны микрофон и установленный BlackHole 2ch. После установки нажми «Обновить устройства».": "A microphone and BlackHole 2ch are required. After installation, click Refresh devices.",
        "Разреши Dota Tilt Guard доступ к микрофону в настройках macOS.": "Allow Dota Tilt Guard to access the microphone in macOS settings.",
        "Микрофон перестал отдавать звук. Проверь подключение и перезапусти защиту.": "The microphone stopped providing audio. Check its connection and restart protection.",
        "Системный микрофон изменился. Перезапусти защиту, чтобы вернуть передачу через фильтр.": "The system microphone changed. Restart protection to route audio through the filter again.",
        "Обнаружено ругательство. Возврат голоса через {0} с.": "Abuse detected. Voice returns in {0} s.",
        "Прежний микрофон отключён.": "The previous microphone is disconnected.",
        "Выбери обычный микрофон в настройках macOS → Звук → Вход: автоматически вернуть его не удалось.": "Select your physical microphone in macOS Settings → Sound → Input. It could not be restored automatically.",
        "Вход: {0} → выход: {1}": "Input: {0} → output: {1}",
        "Микрофон не отдаёт звук. Проверь его подключение.": "The microphone is not providing audio. Check its connection.",
        "Не удалось настроить формат микрофона.": "Could not configure the microphone format.",
        "Аудиоустройство недоступно.": "Audio device unavailable.",
        "Не удалось подключить аудиоустройство ({0}).": "Could not connect the audio device ({0}).",
        "Ошибка преобразования звука.": "Audio conversion failed.",
        "Не удалось выбрать виртуальный микрофон системным входом.": "Could not set the virtual microphone as the system input.",
        "Локальная модель этого языка не установлена. Открой «Установка компонентов» через шестерёнку и загрузи язык.": "The local model for this language is not installed. Open Component setup using the gear button and download the language.",
        "Локальное распознавание не подготовило формат звука.": "Local speech recognition could not prepare an audio format.",
        "Не удалось открыть поток распознавания.": "Could not open the speech recognition stream.",
        "Распознавание остановилось. Перезапусти голосовую защиту.": "Speech recognition stopped. Restart voice protection.",
        "Ошибка локального распознавания: {0}": "Local speech recognition error: {0}",
        "Распознавание не получает звук: {0}": "Speech recognition is not receiving audio: {0}",
        "Не удалось преобразовать звук для распознавания.": "Could not convert audio for speech recognition.",
        "Распознавание не успевает за звуком. Перезапусти голосовую защиту.": "Speech recognition cannot keep up with audio. Restart voice protection.",
        "О Dota Tilt Guard": "About Dota Tilt Guard",
        "Завершить Dota Tilt Guard": "Quit Dota Tilt Guard",
        "Dota Tilt Guard · ⌃⌥Пробел": "Dota Tilt Guard · ⌃⌥Space",
        "Открыть Dota Tilt Guard    ⌃⌥Пробел": "Open Dota Tilt Guard    ⌃⌥Space",
        "Выключить перехват чата": "Turn text protection off",
        "Как пользоваться": "How to use",
        "Завершить": "Quit",
        "Dota Tilt Guard · версия {0}": "Dota Tilt Guard · version {0}",
        "Понятно": "Got it",
        "Разреши Универсальный доступ, включи защиту, вернись в Dota и нажми Esc. После этого открывай чат стандартным Enter. Найденное ругательство остановит отправку. Исправь текст через Backspace или выдели всё через Command+A / Control+A и удали либо замени. После удаления пустой чат можно закрыть Enter. Также можно начать заново через Esc. Сложное редактирование и смена окна требуют повторного Esc.\n\nТекстовый чат проверяется по локальному словарю. Голосовой MVP использует локальное распознавание macOS и BlackHole 2ch: ругательство отключает передачу на 3 секунды, а распознавание продолжает слушать. Аудио и история сообщений не сохраняются. Перехват подключается только к процессу Dota. Приложение не меняет файлы и память игры.\n\nСловарь распознаёт не все оскорбления. При завершении приложения защита прекращается. Окно можно закрывать — приложение продолжит работать в строке меню.": "Allow Accessibility access, enable protection, return to Dota and press Esc. Then open chat with the default Enter key. Detected abuse blocks sending. Use Backspace to edit, or Command+A / Control+A to select all and delete or replace. Once the draft is empty, Enter closes chat. Esc also lets you start again. After complex editing or switching windows, press Esc again.\n\nText chat uses a local dictionary. The voice MVP uses local macOS speech recognition and BlackHole 2ch: detected abuse mutes transmission for 3 seconds while recognition keeps listening. Audio and message history are not saved. Keyboard capture only attaches to Dota. The app does not modify game files or memory.\n\nThe dictionary does not detect all abuse. Quitting the app stops protection. Closing the window keeps the app running in the menu bar."
    ]
}
